In [3]:
import numpy as np

a = np.matrix([[45, 50 ,  90], [789, 98, 80]])
print(a)

[[ 45  50  90]
 [789  98  80]]


In [9]:
print(a[:,2])

[[90]
 [80]]


In [12]:
b = np.zeros((5,2))
a2 = a, b
print(a2)

(matrix([[ 45,  50,  90],
        [789,  98,  80]]), array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]]))


In [18]:
c = np.matrix('45, 45,34;45,367,23')

In [17]:
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
ar = np.arange(60).reshape(6,10)
print(ar)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


In [41]:
ar2 = np.arange(60).reshape(10,6)
print(ar2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


In [47]:
#.T is to transpose a matrix!!
ar3 = ar2.T
print(ar3)

[[ 0  6 12 18 24 30 36 42 48 54]
 [ 1  7 13 19 25 31 37 43 49 55]
 [ 2  8 14 20 26 32 38 44 50 56]
 [ 3  9 15 21 27 33 39 45 51 57]
 [ 4 10 16 22 28 34 40 46 52 58]
 [ 5 11 17 23 29 35 41 47 53 59]]


In [53]:
#use np.dot() instead of *, python uses .dot() to multiply matrices
#ar2*ar3 doesn't work :(
h = np.dot(ar2,ar3)
print(h)

[[   55   145   235   325   415   505   595   685   775   865]
 [  145   451   757  1063  1369  1675  1981  2287  2593  2899]
 [  235   757  1279  1801  2323  2845  3367  3889  4411  4933]
 [  325  1063  1801  2539  3277  4015  4753  5491  6229  6967]
 [  415  1369  2323  3277  4231  5185  6139  7093  8047  9001]
 [  505  1675  2845  4015  5185  6355  7525  8695  9865 11035]
 [  595  1981  3367  4753  6139  7525  8911 10297 11683 13069]
 [  685  2287  3889  5491  7093  8695 10297 11899 13501 15103]
 [  775  2593  4411  6229  8047  9865 11683 13501 15319 17137]
 [  865  2899  4933  6967  9001 11035 13069 15103 17137 19171]]


In [40]:
a = np.matrix('2, 3;3, 4; 1,2')
b = np.matrix('3,2,3;1,1,0')
np.size(a)
np.size(b)


6

In [34]:
a*b


matrix([[ 9,  7,  6],
        [13, 10,  9],
        [ 5,  4,  3]])

In [36]:
b.T*9


matrix([[27,  9],
        [18,  9],
        [27,  0]])

In [56]:
#np.shape() instead of size in matlab
np.shape(h)

(10, 10)

In [57]:
j = np.arange(100).reshape(10,10)
print(j)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [58]:
np.dot(j.T,h)

array([[ 281250,  937350, 1593450, 2249550, 2905650, 3561750, 4217850,
        4873950, 5530050, 6186150],
       [ 285850,  952570, 1619290, 2286010, 2952730, 3619450, 4286170,
        4952890, 5619610, 6286330],
       [ 290450,  967790, 1645130, 2322470, 2999810, 3677150, 4354490,
        5031830, 5709170, 6386510],
       [ 295050,  983010, 1670970, 2358930, 3046890, 3734850, 4422810,
        5110770, 5798730, 6486690],
       [ 299650,  998230, 1696810, 2395390, 3093970, 3792550, 4491130,
        5189710, 5888290, 6586870],
       [ 304250, 1013450, 1722650, 2431850, 3141050, 3850250, 4559450,
        5268650, 5977850, 6687050],
       [ 308850, 1028670, 1748490, 2468310, 3188130, 3907950, 4627770,
        5347590, 6067410, 6787230],
       [ 313450, 1043890, 1774330, 2504770, 3235210, 3965650, 4696090,
        5426530, 6156970, 6887410],
       [ 318050, 1059110, 1800170, 2541230, 3282290, 4023350, 4764410,
        5505470, 6246530, 6987590],
       [ 322650, 1074330, 1826010, 25

In [59]:
np.shape(np.dot(j.T,h))

(10, 10)